# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cnp2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1321, 800)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/bonus/icons-24/system-monitor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.groupBox_voltageBias_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_voltageBias_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_voltageBias_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_voltageBias_3.setObjectName(_fromUtf8("groupBox_voltageBias_3"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.groupBox_voltageBias_3)
        self.verticalLayout_18.setSpacing(3)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_13.setSpacing(10)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_14 = QtGui.QLabel(self.groupBox_voltageBias_3)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_12.addWidget(self.label_14)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        spacerItem1 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.lineEdit_RDCFB = QtGui.QLineEdit(self.groupBox_voltageBias_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lineEdit_RDCFB.sizePolicy().hasHeightForWidth())
        self.lineEdit_RDCFB.setSizePolicy(sizePolicy)
        self.lineEdit_RDCFB.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_RDCFB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_RDCFB.setObjectName(_fromUtf8("lineEdit_RDCFB"))
        self.horizontalLayout_14.addWidget(self.lineEdit_RDCFB)
        spacerItem2 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        spacerItem3 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem3)
        self.label_24 = QtGui.QLabel(self.groupBox_voltageBias_3)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_26.addWidget(self.label_24)
        spacerItem4 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem4)
        self.verticalLayout_11.addLayout(self.horizontalLayout_26)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_9.setHorizontalSpacing(10)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_25 = QtGui.QLabel(self.groupBox_voltageBias_3)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_9.addWidget(self.label_25, 0, 0, 1, 1)
        self.label_IDCOffset = QtGui.QLabel(self.groupBox_voltageBias_3)
        self.label_IDCOffset.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_IDCOffset.setObjectName(_fromUtf8("label_IDCOffset"))
        self.gridLayout_9.addWidget(self.label_IDCOffset, 0, 1, 1, 1)
        self.label_IDCRelative = QtGui.QLabel(self.groupBox_voltageBias_3)
        self.label_IDCRelative.setMinimumSize(QtCore.QSize(0, 0))
        self.label_IDCRelative.setObjectName(_fromUtf8("label_IDCRelative"))
        self.gridLayout_9.addWidget(self.label_IDCRelative, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_voltageBias_3)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_9.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox_voltageBias_3)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_9.addWidget(self.label_26, 1, 0, 1, 1)
        self.label_IDCNet = QtGui.QLabel(self.groupBox_voltageBias_3)
        self.label_IDCNet.setMinimumSize(QtCore.QSize(0, 0))
        self.label_IDCNet.setObjectName(_fromUtf8("label_IDCNet"))
        self.gridLayout_9.addWidget(self.label_IDCNet, 2, 1, 1, 1)
        self.pushButton_IDCSetOffset = QtGui.QPushButton(self.groupBox_voltageBias_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_IDCSetOffset.sizePolicy().hasHeightForWidth())
        self.pushButton_IDCSetOffset.setSizePolicy(sizePolicy)
        self.pushButton_IDCSetOffset.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_IDCSetOffset.setMaximumSize(QtCore.QSize(40, 20))
        self.pushButton_IDCSetOffset.setObjectName(_fromUtf8("pushButton_IDCSetOffset"))
        self.gridLayout_9.addWidget(self.pushButton_IDCSetOffset, 0, 2, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_9)
        self.verticalLayout_13.addLayout(self.verticalLayout_11)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem5 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.label_11 = QtGui.QLabel(self.groupBox_voltageBias_3)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_13.addWidget(self.label_11)
        spacerItem6 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setHorizontalSpacing(10)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_12 = QtGui.QLabel(self.groupBox_voltageBias_3)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_8.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_100kHzNoise = QtGui.QLabel(self.groupBox_voltageBias_3)
        self.label_100kHzNoise.setObjectName(_fromUtf8("label_100kHzNoise"))
        self.gridLayout_8.addWidget(self.label_100kHzNoise, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_voltageBias_3)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_8.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_1MHzNoise = QtGui.QLabel(self.groupBox_voltageBias_3)
        self.label_1MHzNoise.setObjectName(_fromUtf8("label_1MHzNoise"))
        self.gridLayout_8.addWidget(self.label_1MHzNoise, 1, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_voltageBias_3)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_8.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_10MHzNoise = QtGui.QLabel(self.groupBox_voltageBias_3)
        self.label_10MHzNoise.setObjectName(_fromUtf8("label_10MHzNoise"))
        self.gridLayout_8.addWidget(self.label_10MHzNoise, 2, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_8)
        self.verticalLayout_13.addLayout(self.verticalLayout_9)
        self.verticalLayout_18.addLayout(self.verticalLayout_13)
        self.verticalLayout_7.addWidget(self.groupBox_voltageBias_3)
        self.horizontalLayout_20.addLayout(self.verticalLayout_7)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        spacerItem7 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem7)
        self.groupBox_voltageBias_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_voltageBias_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_voltageBias_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_voltageBias_2.setObjectName(_fromUtf8("groupBox_voltageBias_2"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_voltageBias_2)
        self.verticalLayout_14.setSpacing(3)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_voltageBias_2)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_16.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_16.setSpacing(3)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.checkBox_ADC0enable = QtGui.QCheckBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_ADC0enable.sizePolicy().hasHeightForWidth())
        self.checkBox_ADC0enable.setSizePolicy(sizePolicy)
        self.checkBox_ADC0enable.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_ADC0enable.setChecked(True)
        self.checkBox_ADC0enable.setObjectName(_fromUtf8("checkBox_ADC0enable"))
        self.gridLayout_2.addWidget(self.checkBox_ADC0enable, 1, 2, 1, 1)
        self.checkBox_ADCenable = QtGui.QCheckBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_ADCenable.sizePolicy().hasHeightForWidth())
        self.checkBox_ADCenable.setSizePolicy(sizePolicy)
        self.checkBox_ADCenable.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_ADCenable.setChecked(True)
        self.checkBox_ADCenable.setObjectName(_fromUtf8("checkBox_ADCenable"))
        self.gridLayout_2.addWidget(self.checkBox_ADCenable, 0, 2, 1, 1)
        self.checkBox_ADC2enable = QtGui.QCheckBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_ADC2enable.sizePolicy().hasHeightForWidth())
        self.checkBox_ADC2enable.setSizePolicy(sizePolicy)
        self.checkBox_ADC2enable.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_ADC2enable.setChecked(True)
        self.checkBox_ADC2enable.setObjectName(_fromUtf8("checkBox_ADC2enable"))
        self.gridLayout_2.addWidget(self.checkBox_ADC2enable, 3, 2, 1, 1)
        self.checkBox_ADC4enable = QtGui.QCheckBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_ADC4enable.sizePolicy().hasHeightForWidth())
        self.checkBox_ADC4enable.setSizePolicy(sizePolicy)
        self.checkBox_ADC4enable.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_ADC4enable.setChecked(True)
        self.checkBox_ADC4enable.setObjectName(_fromUtf8("checkBox_ADC4enable"))
        self.gridLayout_2.addWidget(self.checkBox_ADC4enable, 5, 2, 1, 1)
        self.checkBox_ADC1enable = QtGui.QCheckBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_ADC1enable.sizePolicy().hasHeightForWidth())
        self.checkBox_ADC1enable.setSizePolicy(sizePolicy)
        self.checkBox_ADC1enable.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_ADC1enable.setChecked(True)
        self.checkBox_ADC1enable.setObjectName(_fromUtf8("checkBox_ADC1enable"))
        self.gridLayout_2.addWidget(self.checkBox_ADC1enable, 2, 2, 1, 1)
        self.checkBox_ADC3enable = QtGui.QCheckBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_ADC3enable.sizePolicy().hasHeightForWidth())
        self.checkBox_ADC3enable.setSizePolicy(sizePolicy)
        self.checkBox_ADC3enable.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_ADC3enable.setChecked(True)
        self.checkBox_ADC3enable.setObjectName(_fromUtf8("checkBox_ADC3enable"))
        self.gridLayout_2.addWidget(self.checkBox_ADC3enable, 4, 2, 1, 1)
        self.verticalLayout_15.addLayout(self.gridLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEdit_getDataFileSelect = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_getDataFileSelect.sizePolicy().hasHeightForWidth())
        self.lineEdit_getDataFileSelect.setSizePolicy(sizePolicy)
        self.lineEdit_getDataFileSelect.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_getDataFileSelect.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_getDataFileSelect.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_getDataFileSelect.setObjectName(_fromUtf8("lineEdit_getDataFileSelect"))
        self.horizontalLayout.addWidget(self.lineEdit_getDataFileSelect)
        self.pushButton_getDataFileSelect = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_getDataFileSelect.sizePolicy().hasHeightForWidth())
        self.pushButton_getDataFileSelect.setSizePolicy(sizePolicy)
        self.pushButton_getDataFileSelect.setMaximumSize(QtCore.QSize(31, 23))
        self.pushButton_getDataFileSelect.setObjectName(_fromUtf8("pushButton_getDataFileSelect"))
        self.horizontalLayout.addWidget(self.pushButton_getDataFileSelect)
        self.verticalLayout_15.addLayout(self.horizontalLayout)
        self.horizontalLayout_18.addLayout(self.verticalLayout_15)
        spacerItem8 = QtGui.QSpacerItem(10, 10, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem8)
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.comboBox_rowSelect = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_rowSelect.setObjectName(_fromUtf8("comboBox_rowSelect"))
        self.comboBox_rowSelect.addItem(_fromUtf8(""))
        self.comboBox_rowSelect.addItem(_fromUtf8(""))
        self.comboBox_rowSelect.addItem(_fromUtf8(""))
        self.comboBox_rowSelect.addItem(_fromUtf8(""))
        self.comboBox_rowSelect.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_rowSelect, 0, 1, 1, 1)
        self.comboBox_amplifierGainSelect = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_amplifierGainSelect.setObjectName(_fromUtf8("comboBox_amplifierGainSelect"))
        self.comboBox_amplifierGainSelect.addItem(_fromUtf8(""))
        self.comboBox_amplifierGainSelect.addItem(_fromUtf8(""))
        self.comboBox_amplifierGainSelect.addItem(_fromUtf8(""))
        self.comboBox_amplifierGainSelect.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_amplifierGainSelect, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.comboBox_columnSelect = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_columnSelect.setObjectName(_fromUtf8("comboBox_columnSelect"))
        self.comboBox_columnSelect.addItem(_fromUtf8(""))
        self.comboBox_columnSelect.addItem(_fromUtf8(""))
        self.comboBox_columnSelect.addItem(_fromUtf8(""))
        self.comboBox_columnSelect.addItem(_fromUtf8(""))
        self.comboBox_columnSelect.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_columnSelect, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.horizontalLayout_17.addLayout(self.gridLayout)
        self.pushButton_programChip = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_programChip.sizePolicy().hasHeightForWidth())
        self.pushButton_programChip.setSizePolicy(sizePolicy)
        self.pushButton_programChip.setObjectName(_fromUtf8("pushButton_programChip"))
        self.horizontalLayout_17.addWidget(self.pushButton_programChip)
        self.verticalLayout_23.addLayout(self.horizontalLayout_17)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.checkBox_biasEnable = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_biasEnable.setObjectName(_fromUtf8("checkBox_biasEnable"))
        self.gridLayout_5.addWidget(self.checkBox_biasEnable, 0, 0, 1, 1)
        self.checkBox_integratorReset = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_integratorReset.setObjectName(_fromUtf8("checkBox_integratorReset"))
        self.gridLayout_5.addWidget(self.checkBox_integratorReset, 0, 1, 1, 1)
        self.checkBox_connectElectrode = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_connectElectrode.setObjectName(_fromUtf8("checkBox_connectElectrode"))
        self.gridLayout_5.addWidget(self.checkBox_connectElectrode, 1, 0, 1, 1)
        self.checkBox_connectISRCEXT = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_connectISRCEXT.setObjectName(_fromUtf8("checkBox_connectISRCEXT"))
        self.gridLayout_5.addWidget(self.checkBox_connectISRCEXT, 1, 1, 1, 1)
        self.checkBox_enableSwitchedCapClock = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_enableSwitchedCapClock.setEnabled(False)
        self.checkBox_enableSwitchedCapClock.setObjectName(_fromUtf8("checkBox_enableSwitchedCapClock"))
        self.gridLayout_5.addWidget(self.checkBox_enableSwitchedCapClock, 2, 0, 1, 1)
        self.checkBox_frequencyResponse = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_frequencyResponse.setObjectName(_fromUtf8("checkBox_frequencyResponse"))
        self.gridLayout_5.addWidget(self.checkBox_frequencyResponse, 2, 1, 1, 1)
        self.checkBox_enableTriangleWave = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_enableTriangleWave.setObjectName(_fromUtf8("checkBox_enableTriangleWave"))
        self.gridLayout_5.addWidget(self.checkBox_enableTriangleWave, 3, 0, 1, 1)
        self.verticalLayout_23.addLayout(self.gridLayout_5)
        self.horizontalLayout_18.addLayout(self.verticalLayout_23)
        self.verticalLayout_16.addLayout(self.horizontalLayout_18)
        self.verticalLayout_14.addWidget(self.groupBox_4)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem9 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_voltageBias_2)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_31.setSpacing(3)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setSpacing(3)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.checkBox_enableSquareWave = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_enableSquareWave.setObjectName(_fromUtf8("checkBox_enableSquareWave"))
        self.verticalLayout_10.addWidget(self.checkBox_enableSquareWave, QtCore.Qt.AlignHCenter)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_poreResistance_name = QtGui.QLabel(self.groupBox_7)
        self.label_poreResistance_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_poreResistance_name.setObjectName(_fromUtf8("label_poreResistance_name"))
        self.gridLayout_6.addWidget(self.label_poreResistance_name, 0, 0, 1, 1)
        self.label_poreResistance = QtGui.QLabel(self.groupBox_7)
        self.label_poreResistance.setObjectName(_fromUtf8("label_poreResistance"))
        self.gridLayout_6.addWidget(self.label_poreResistance, 0, 1, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_6)
        self.horizontalLayout_31.addLayout(self.verticalLayout_10)
        self.verticalLayout_22.addWidget(self.groupBox_7)
        spacerItem10 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_22.addItem(spacerItem10)
        self.horizontalLayout_9.addLayout(self.verticalLayout_22)
        spacerItem11 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_24.setSpacing(6)
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_voltageBias_2)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_30.setSpacing(3)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBox_enableLivePreviewFilter = QtGui.QCheckBox(self.groupBox_6)
        self.checkBox_enableLivePreviewFilter.setMaximumSize(QtCore.QSize(16777215, 17))
        self.checkBox_enableLivePreviewFilter.setObjectName(_fromUtf8("checkBox_enableLivePreviewFilter"))
        self.verticalLayout_3.addWidget(self.checkBox_enableLivePreviewFilter, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lineEdit_livePreviewFilterBandwidth = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_livePreviewFilterBandwidth.setMaximumSize(QtCore.QSize(56, 20))
        self.lineEdit_livePreviewFilterBandwidth.setText(_fromUtf8(""))
        self.lineEdit_livePreviewFilterBandwidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_livePreviewFilterBandwidth.setObjectName(_fromUtf8("lineEdit_livePreviewFilterBandwidth"))
        self.horizontalLayout_4.addWidget(self.lineEdit_livePreviewFilterBandwidth)
        self.label_20 = QtGui.QLabel(self.groupBox_6)
        self.label_20.setMaximumSize(QtCore.QSize(31, 20))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_4.addWidget(self.label_20)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_30.addLayout(self.verticalLayout_3)
        self.verticalLayout_24.addWidget(self.groupBox_6)
        spacerItem12 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem12)
        self.horizontalLayout_9.addLayout(self.verticalLayout_24)
        spacerItem13 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem13)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_voltageBias_2)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_29.setSpacing(3)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSpacing(3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_28 = QtGui.QLabel(self.groupBox_5)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_3.addWidget(self.label_28, 1, 2, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_5)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_3.addWidget(self.label_27, 1, 1, 1, 1)
        self.label_FPGASlaveBufferUtilization = QtGui.QLabel(self.groupBox_5)
        self.label_FPGASlaveBufferUtilization.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_FPGASlaveBufferUtilization.setObjectName(_fromUtf8("label_FPGASlaveBufferUtilization"))
        self.gridLayout_3.addWidget(self.label_FPGASlaveBufferUtilization, 3, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 3, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_5)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 1)
        self.label_FPGAMasterStatus_icon = QtGui.QLabel(self.groupBox_5)
        self.label_FPGAMasterStatus_icon.setText(_fromUtf8(""))
        self.label_FPGAMasterStatus_icon.setPixmap(QtGui.QPixmap(_fromUtf8("Icons/icons/status-busy.png")))
        self.label_FPGAMasterStatus_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.label_FPGAMasterStatus_icon.setObjectName(_fromUtf8("label_FPGAMasterStatus_icon"))
        self.gridLayout_3.addWidget(self.label_FPGAMasterStatus_icon, 2, 1, 1, 1)
        self.label_FPGAMasterBufferUtilization = QtGui.QLabel(self.groupBox_5)
        self.label_FPGAMasterBufferUtilization.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_FPGAMasterBufferUtilization.setObjectName(_fromUtf8("label_FPGAMasterBufferUtilization"))
        self.gridLayout_3.addWidget(self.label_FPGAMasterBufferUtilization, 2, 2, 1, 1)
        self.label_FPGASlaveStatus_icon = QtGui.QLabel(self.groupBox_5)
        self.label_FPGASlaveStatus_icon.setText(_fromUtf8(""))
        self.label_FPGASlaveStatus_icon.setPixmap(QtGui.QPixmap(_fromUtf8("Icons/icons/status-busy.png")))
        self.label_FPGASlaveStatus_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.label_FPGASlaveStatus_icon.setObjectName(_fromUtf8("label_FPGASlaveStatus_icon"))
        self.gridLayout_3.addWidget(self.label_FPGASlaveStatus_icon, 3, 1, 1, 1)
        self.horizontalLayout_29.addLayout(self.gridLayout_3)
        self.horizontalLayout_9.addWidget(self.groupBox_5)
        spacerItem14 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem14)
        self.verticalLayout_14.addLayout(self.horizontalLayout_9)
        self.verticalLayout_17.addWidget(self.groupBox_voltageBias_2)
        self.horizontalLayout_20.addLayout(self.verticalLayout_17)
        self.groupBox_voltageBias = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_voltageBias.setEnabled(True)
        self.groupBox_voltageBias.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_voltageBias.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_voltageBias.setObjectName(_fromUtf8("groupBox_voltageBias"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_voltageBias)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem15 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem15)
        self.lineEdit_counterelectrodePotential = QtGui.QLineEdit(self.groupBox_voltageBias)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_counterelectrodePotential.sizePolicy().hasHeightForWidth())
        self.lineEdit_counterelectrodePotential.setSizePolicy(sizePolicy)
        self.lineEdit_counterelectrodePotential.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_counterelectrodePotential.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_counterelectrodePotential.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_counterelectrodePotential.setReadOnly(True)
        self.lineEdit_counterelectrodePotential.setObjectName(_fromUtf8("lineEdit_counterelectrodePotential"))
        self.horizontalLayout_8.addWidget(self.lineEdit_counterelectrodePotential)
        self.label_8 = QtGui.QLabel(self.groupBox_voltageBias)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_8.addWidget(self.label_8)
        spacerItem16 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem16)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.groupBox = QtGui.QGroupBox(self.groupBox_voltageBias)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton_counterelectrodePotentialZero_absolute = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_counterelectrodePotentialZero_absolute.sizePolicy().hasHeightForWidth())
        self.pushButton_counterelectrodePotentialZero_absolute.setSizePolicy(sizePolicy)
        self.pushButton_counterelectrodePotentialZero_absolute.setObjectName(_fromUtf8("pushButton_counterelectrodePotentialZero_absolute"))
        self.horizontalLayout_5.addWidget(self.pushButton_counterelectrodePotentialZero_absolute)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_counterelectrodePotentialPlus900_absolute = QtGui.QPushButton(self.groupBox)
        self.pushButton_counterelectrodePotentialPlus900_absolute.setObjectName(_fromUtf8("pushButton_counterelectrodePotentialPlus900_absolute"))
        self.verticalLayout.addWidget(self.pushButton_counterelectrodePotentialPlus900_absolute)
        self.pushButton_counterelectrodePotentialPlus500_absolute = QtGui.QPushButton(self.groupBox)
        self.pushButton_counterelectrodePotentialPlus500_absolute.setObjectName(_fromUtf8("pushButton_counterelectrodePotentialPlus500_absolute"))
        self.verticalLayout.addWidget(self.pushButton_counterelectrodePotentialPlus500_absolute)
        self.pushButton_counterelectrodePotentialPlus400_absolute = QtGui.QPushButton(self.groupBox)
        self.pushButton_counterelectrodePotentialPlus400_absolute.setObjectName(_fromUtf8("pushButton_counterelectrodePotentialPlus400_absolute"))
        self.verticalLayout.addWidget(self.pushButton_counterelectrodePotentialPlus400_absolute)
        self.pushButton_counterelectrodePotentialPlus300_absolute = QtGui.QPushButton(self.groupBox)
        self.pushButton_counterelectrodePotentialPlus300_absolute.setObjectName(_fromUtf8("pushButton_counterelectrodePotentialPlus300_absolute"))
        self.verticalLayout.addWidget(self.pushButton_counterelectrodePotentialPlus300_absolute)
        self.pushButton_counterelectrodePotentialPlus200_absolute = QtGui.QPushButton(self.groupBox)
        self.pushButton_counterelectrodePotentialPlus200_absolute.setObjectName(_fromUtf8("pushButton_counterelectrodePotentialPlus200_absolute"))
        self.verticalLayout.addWidget(self.pushButton_counterelectrodePotentialPlus200_absolute)
        self.pushButton_counterelectrodePotentialPlus100_absolute = QtGui.QPushButton(self.groupBox)
        self.pushButton_counterelectrodePotentialPlus100_absolute.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_counterelectrodePotentialPlus100_absolute.setObjectName(_fromUtf8("pushButton_counterelectrodePotentialPlus100_absolute"))
        self.verticalLayout.addWidget(self.pushButton_counterelectrodePotentialPlus100_absolute)
        self.pushButton_counterelectrodePotentialPlus50_absolute = QtGui.QPushButton(self.groupBox)
        self.pushButton_counterelectrodePotentialPlus50_absolute.setObjectName(_fromUtf8("pushButton_counterelectrodePotentialPlus50_absolute"))
        self.verticalLayout.addWidget(self.pushButton_counterelectrodePotentialPlus50_absolute)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButton_counterelectrodePotentialMinus900_absolute = QtGui.QPushButton(self.groupBox)
        self.pushButton_counterelectrodePotentialMinus900_absolute.setObjectName(_fromUtf8("pushButton_counterelectrodePotentialMinus900_absolute"))
        self.verticalLayout_2.addWidget(self.pushButton_counterelectrodePotentialMinus900_absolute)
        self.pushButton_counterelectrodePotentialMinus500_absolute = QtGui.QPushButton(self.groupBox)
        self.pushButton_counterelectrodePotentialMinus500_absolute.setObjectName(_fromUtf8("pushButton_counterelectrodePotentialMinus500_absolute"))
        self.verticalLayout_2.addWidget(self.pushButton_counterelectrodePotentialMinus500_absolute)
        self.pushButton_counterelectrodePotentialMinus400_absolute = QtGui.QPushButton(self.groupBox)
        self.pushButton_counterelectrodePotentialMinus400_absolute.setObjectName(_fromUtf8("pushButton_counterelectrodePotentialMinus400_absolute"))
        self.verticalLayout_2.addWidget(self.pushButton_counterelectrodePotentialMinus400_absolute)
        self.pushButton_counterelectrodePotentialMinus300_absolute = QtGui.QPushButton(self.groupBox)
        self.pushButton_counterelectrodePotentialMinus300_absolute.setObjectName(_fromUtf8("pushButton_counterelectrodePotentialMinus300_absolute"))
        self.verticalLayout_2.addWidget(self.pushButton_counterelectrodePotentialMinus300_absolute)
        self.pushButton_counterelectrodePotentialMinus200_absolute = QtGui.QPushButton(self.groupBox)
        self.pushButton_counterelectrodePotentialMinus200_absolute.setObjectName(_fromUtf8("pushButton_counterelectrodePotentialMinus200_absolute"))
        self.verticalLayout_2.addWidget(self.pushButton_counterelectrodePotentialMinus200_absolute)
        self.pushButton_counterelectrodePotentialMinus100_absolute = QtGui.QPushButton(self.groupBox)
        self.pushButton_counterelectrodePotentialMinus100_absolute.setObjectName(_fromUtf8("pushButton_counterelectrodePotentialMinus100_absolute"))
        self.verticalLayout_2.addWidget(self.pushButton_counterelectrodePotentialMinus100_absolute)
        self.pushButton_counterelectrodePotentialMinus50_absolute = QtGui.QPushButton(self.groupBox)
        self.pushButton_counterelectrodePotentialMinus50_absolute.setObjectName(_fromUtf8("pushButton_counterelectrodePotentialMinus50_absolute"))
        self.verticalLayout_2.addWidget(self.pushButton_counterelectrodePotentialMinus50_absolute)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox1 = QtGui.QGroupBox(self.groupBox_voltageBias)
        self.groupBox1.setObjectName(_fromUtf8("groupBox1"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox1)
        self.horizontalLayout_7.setSpacing(3)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem17 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem17)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_7.setSpacing(3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.pushButton_counterelectrodePotentialMinus10_relative = QtGui.QPushButton(self.groupBox1)
        self.pushButton_counterelectrodePotentialMinus10_relative.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_counterelectrodePotentialMinus10_relative.setObjectName(_fromUtf8("pushButton_counterelectrodePotentialMinus10_relative"))
        self.gridLayout_7.addWidget(self.pushButton_counterelectrodePotentialMinus10_relative, 1, 2, 1, 1)
        self.pushButton_counterelectrodePotentialPlus10_relative = QtGui.QPushButton(self.groupBox1)
        self.pushButton_counterelectrodePotentialPlus10_relative.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_counterelectrodePotentialPlus10_relative.setObjectName(_fromUtf8("pushButton_counterelectrodePotentialPlus10_relative"))
        self.gridLayout_7.addWidget(self.pushButton_counterelectrodePotentialPlus10_relative, 0, 2, 1, 1)
        self.pushButton_counterelectrodePotentialPlus100_relative = QtGui.QPushButton(self.groupBox1)
        self.pushButton_counterelectrodePotentialPlus100_relative.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_counterelectrodePotentialPlus100_relative.setObjectName(_fromUtf8("pushButton_counterelectrodePotentialPlus100_relative"))
        self.gridLayout_7.addWidget(self.pushButton_counterelectrodePotentialPlus100_relative, 0, 0, 1, 1)
        self.pushButton_counterelectrodePotentialMinus50_relative = QtGui.QPushButton(self.groupBox1)
        self.pushButton_counterelectrodePotentialMinus50_relative.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_counterelectrodePotentialMinus50_relative.setObjectName(_fromUtf8("pushButton_counterelectrodePotentialMinus50_relative"))
        self.gridLayout_7.addWidget(self.pushButton_counterelectrodePotentialMinus50_relative, 1, 1, 1, 1)
        self.pushButton_counterelectrodePotentialMinus100_relative = QtGui.QPushButton(self.groupBox1)
        self.pushButton_counterelectrodePotentialMinus100_relative.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_counterelectrodePotentialMinus100_relative.setObjectName(_fromUtf8("pushButton_counterelectrodePotentialMinus100_relative"))
        self.gridLayout_7.addWidget(self.pushButton_counterelectrodePotentialMinus100_relative, 1, 0, 1, 1)
        self.pushButton_counterelectrodePotentialPlus50_relative = QtGui.QPushButton(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_counterelectrodePotentialPlus50_relative.sizePolicy().hasHeightForWidth())
        self.pushButton_counterelectrodePotentialPlus50_relative.setSizePolicy(sizePolicy)
        self.pushButton_counterelectrodePotentialPlus50_relative.setMinimumSize(QtCore.QSize(10, 0))
        self.pushButton_counterelectrodePotentialPlus50_relative.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_counterelectrodePotentialPlus50_relative.setObjectName(_fromUtf8("pushButton_counterelectrodePotentialPlus50_relative"))
        self.gridLayout_7.addWidget(self.pushButton_counterelectrodePotentialPlus50_relative, 0, 1, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_7)
        spacerItem18 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem18)
        self.verticalLayout_6.addWidget(self.groupBox1)
        self.horizontalLayout_20.addWidget(self.groupBox_voltageBias)
        self.verticalLayout_21.addLayout(self.horizontalLayout_20)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem19)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.lineEdit_logDuration = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_logDuration.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_logDuration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_logDuration.setObjectName(_fromUtf8("lineEdit_logDuration"))
        self.horizontalLayout_2.addWidget(self.lineEdit_logDuration)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.tabWidget_plot = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget_plot.sizePolicy().hasHeightForWidth())
        self.tabWidget_plot.setSizePolicy(sizePolicy)
        self.tabWidget_plot.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget_plot.setObjectName(_fromUtf8("tabWidget_plot"))
        self.tab_time = QtGui.QWidget()
        self.tab_time.setObjectName(_fromUtf8("tab_time"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.tab_time)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.graphicsView_time = PlotWidget(self.tab_time)
        self.graphicsView_time.setObjectName(_fromUtf8("graphicsView_time"))
        self.horizontalLayout_10.addWidget(self.graphicsView_time)
        self.tabWidget_plot.addTab(self.tab_time, _fromUtf8(""))
        self.tab_frequency = QtGui.QWidget()
        self.tab_frequency.setObjectName(_fromUtf8("tab_frequency"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.tab_frequency)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.graphicsView_frequency = PlotWidget(self.tab_frequency)
        self.graphicsView_frequency.setObjectName(_fromUtf8("graphicsView_frequency"))
        self.horizontalLayout_11.addWidget(self.graphicsView_frequency)
        self.tabWidget_plot.addTab(self.tab_frequency, _fromUtf8(""))
        self.tab_histogram = QtGui.QWidget()
        self.tab_histogram.setObjectName(_fromUtf8("tab_histogram"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.tab_histogram)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.graphicsView_histogram = PlotWidget(self.tab_histogram)
        self.graphicsView_histogram.setObjectName(_fromUtf8("graphicsView_histogram"))
        self.horizontalLayout_12.addWidget(self.graphicsView_histogram)
        self.tabWidget_plot.addTab(self.tab_histogram, _fromUtf8(""))
        self.tab_IV = QtGui.QWidget()
        self.tab_IV.setObjectName(_fromUtf8("tab_IV"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.tab_IV)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.graphicsView_IV = PlotWidget(self.tab_IV)
        self.graphicsView_IV.setObjectName(_fromUtf8("graphicsView_IV"))
        self.horizontalLayout_28.addWidget(self.graphicsView_IV)
        self.tabWidget_plot.addTab(self.tab_IV, _fromUtf8(""))
        self.verticalLayout_8.addWidget(self.tabWidget_plot)
        self.verticalLayout_21.addLayout(self.verticalLayout_8)
        self.horizontalLayout_16.addLayout(self.verticalLayout_21)
        self.verticalLayout_rowPlot = QtGui.QVBoxLayout()
        self.verticalLayout_rowPlot.setObjectName(_fromUtf8("verticalLayout_rowPlot"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem20)
        self.checkBox_rowPlot_enable = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_rowPlot_enable.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_rowPlot_enable.setObjectName(_fromUtf8("checkBox_rowPlot_enable"))
        self.horizontalLayout_21.addWidget(self.checkBox_rowPlot_enable)
        self.label_rowPlot_rowSelect_label = QtGui.QLabel(self.centralwidget)
        self.label_rowPlot_rowSelect_label.setObjectName(_fromUtf8("label_rowPlot_rowSelect_label"))
        self.horizontalLayout_21.addWidget(self.label_rowPlot_rowSelect_label)
        self.comboBox_rowSelect_2 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_rowSelect_2.setObjectName(_fromUtf8("comboBox_rowSelect_2"))
        self.comboBox_rowSelect_2.addItem(_fromUtf8(""))
        self.comboBox_rowSelect_2.addItem(_fromUtf8(""))
        self.comboBox_rowSelect_2.addItem(_fromUtf8(""))
        self.comboBox_rowSelect_2.addItem(_fromUtf8(""))
        self.comboBox_rowSelect_2.addItem(_fromUtf8(""))
        self.horizontalLayout_21.addWidget(self.comboBox_rowSelect_2)
        self.label_rowPlot_logDuration = QtGui.QLabel(self.centralwidget)
        self.label_rowPlot_logDuration.setObjectName(_fromUtf8("label_rowPlot_logDuration"))
        self.horizontalLayout_21.addWidget(self.label_rowPlot_logDuration)
        self.lineEdit_rowPlot_logDuration = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_rowPlot_logDuration.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_rowPlot_logDuration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_rowPlot_logDuration.setObjectName(_fromUtf8("lineEdit_rowPlot_logDuration"))
        self.horizontalLayout_21.addWidget(self.lineEdit_rowPlot_logDuration)
        self.verticalLayout_rowPlot.addLayout(self.horizontalLayout_21)
        self.tabWidget_rowPlot = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget_rowPlot.sizePolicy().hasHeightForWidth())
        self.tabWidget_rowPlot.setSizePolicy(sizePolicy)
        self.tabWidget_rowPlot.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget_rowPlot.setObjectName(_fromUtf8("tabWidget_rowPlot"))
        self.tab_time_rowPlot = QtGui.QWidget()
        self.tab_time_rowPlot.setObjectName(_fromUtf8("tab_time_rowPlot"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.tab_time_rowPlot)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.verticalLayout_26 = QtGui.QVBoxLayout()
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.graphicsView_time_column0 = PlotWidget(self.tab_time_rowPlot)
        self.graphicsView_time_column0.setObjectName(_fromUtf8("graphicsView_time_column0"))
        self.verticalLayout_26.addWidget(self.graphicsView_time_column0)
        self.graphicsView_time_column1 = PlotWidget(self.tab_time_rowPlot)
        self.graphicsView_time_column1.setObjectName(_fromUtf8("graphicsView_time_column1"))
        self.verticalLayout_26.addWidget(self.graphicsView_time_column1)
        self.graphicsView_time_column2 = PlotWidget(self.tab_time_rowPlot)
        self.graphicsView_time_column2.setObjectName(_fromUtf8("graphicsView_time_column2"))
        self.verticalLayout_26.addWidget(self.graphicsView_time_column2)
        self.graphicsView_time_column3 = PlotWidget(self.tab_time_rowPlot)
        self.graphicsView_time_column3.setObjectName(_fromUtf8("graphicsView_time_column3"))
        self.verticalLayout_26.addWidget(self.graphicsView_time_column3)
        self.graphicsView_time_column4 = PlotWidget(self.tab_time_rowPlot)
        self.graphicsView_time_column4.setObjectName(_fromUtf8("graphicsView_time_column4"))
        self.verticalLayout_26.addWidget(self.graphicsView_time_column4)
        self.horizontalLayout_22.addLayout(self.verticalLayout_26)
        self.tabWidget_rowPlot.addTab(self.tab_time_rowPlot, _fromUtf8(""))
        self.tab_frequency_rowPlot = QtGui.QWidget()
        self.tab_frequency_rowPlot.setObjectName(_fromUtf8("tab_frequency_rowPlot"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.tab_frequency_rowPlot)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.verticalLayout_27 = QtGui.QVBoxLayout()
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.graphicsView_frequency_column0 = PlotWidget(self.tab_frequency_rowPlot)
        self.graphicsView_frequency_column0.setObjectName(_fromUtf8("graphicsView_frequency_column0"))
        self.verticalLayout_27.addWidget(self.graphicsView_frequency_column0)
        self.graphicsView_frequency_column1 = PlotWidget(self.tab_frequency_rowPlot)
        self.graphicsView_frequency_column1.setObjectName(_fromUtf8("graphicsView_frequency_column1"))
        self.verticalLayout_27.addWidget(self.graphicsView_frequency_column1)
        self.graphicsView_frequency_column2 = PlotWidget(self.tab_frequency_rowPlot)
        self.graphicsView_frequency_column2.setObjectName(_fromUtf8("graphicsView_frequency_column2"))
        self.verticalLayout_27.addWidget(self.graphicsView_frequency_column2)
        self.graphicsView_frequency_column3 = PlotWidget(self.tab_frequency_rowPlot)
        self.graphicsView_frequency_column3.setObjectName(_fromUtf8("graphicsView_frequency_column3"))
        self.verticalLayout_27.addWidget(self.graphicsView_frequency_column3)
        self.graphicsView_frequency_column4 = PlotWidget(self.tab_frequency_rowPlot)
        self.graphicsView_frequency_column4.setObjectName(_fromUtf8("graphicsView_frequency_column4"))
        self.verticalLayout_27.addWidget(self.graphicsView_frequency_column4)
        self.horizontalLayout_23.addLayout(self.verticalLayout_27)
        self.tabWidget_rowPlot.addTab(self.tab_frequency_rowPlot, _fromUtf8(""))
        self.tab_histogram_rowPlot = QtGui.QWidget()
        self.tab_histogram_rowPlot.setObjectName(_fromUtf8("tab_histogram_rowPlot"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.tab_histogram_rowPlot)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.verticalLayout_30 = QtGui.QVBoxLayout()
        self.verticalLayout_30.setObjectName(_fromUtf8("verticalLayout_30"))
        self.graphicsView_histogram_column0 = PlotWidget(self.tab_histogram_rowPlot)
        self.graphicsView_histogram_column0.setObjectName(_fromUtf8("graphicsView_histogram_column0"))
        self.verticalLayout_30.addWidget(self.graphicsView_histogram_column0)
        self.graphicsView_histogram_column1 = PlotWidget(self.tab_histogram_rowPlot)
        self.graphicsView_histogram_column1.setObjectName(_fromUtf8("graphicsView_histogram_column1"))
        self.verticalLayout_30.addWidget(self.graphicsView_histogram_column1)
        self.graphicsView_histogram_column2 = PlotWidget(self.tab_histogram_rowPlot)
        self.graphicsView_histogram_column2.setObjectName(_fromUtf8("graphicsView_histogram_column2"))
        self.verticalLayout_30.addWidget(self.graphicsView_histogram_column2)
        self.graphicsView_histogram_column3 = PlotWidget(self.tab_histogram_rowPlot)
        self.graphicsView_histogram_column3.setObjectName(_fromUtf8("graphicsView_histogram_column3"))
        self.verticalLayout_30.addWidget(self.graphicsView_histogram_column3)
        self.graphicsView_histogram_column4 = PlotWidget(self.tab_histogram_rowPlot)
        self.graphicsView_histogram_column4.setObjectName(_fromUtf8("graphicsView_histogram_column4"))
        self.verticalLayout_30.addWidget(self.graphicsView_histogram_column4)
        self.horizontalLayout_24.addLayout(self.verticalLayout_30)
        self.tabWidget_rowPlot.addTab(self.tab_histogram_rowPlot, _fromUtf8(""))
        self.tab_IV_rowPlot = QtGui.QWidget()
        self.tab_IV_rowPlot.setObjectName(_fromUtf8("tab_IV_rowPlot"))
        self.horizontalLayout_32 = QtGui.QHBoxLayout(self.tab_IV_rowPlot)
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.verticalLayout_32 = QtGui.QVBoxLayout()
        self.verticalLayout_32.setObjectName(_fromUtf8("verticalLayout_32"))
        self.graphicsView_IV_column0 = PlotWidget(self.tab_IV_rowPlot)
        self.graphicsView_IV_column0.setObjectName(_fromUtf8("graphicsView_IV_column0"))
        self.verticalLayout_32.addWidget(self.graphicsView_IV_column0)
        self.graphicsView_IV_column1 = PlotWidget(self.tab_IV_rowPlot)
        self.graphicsView_IV_column1.setObjectName(_fromUtf8("graphicsView_IV_column1"))
        self.verticalLayout_32.addWidget(self.graphicsView_IV_column1)
        self.graphicsView_IV_column2 = PlotWidget(self.tab_IV_rowPlot)
        self.graphicsView_IV_column2.setObjectName(_fromUtf8("graphicsView_IV_column2"))
        self.verticalLayout_32.addWidget(self.graphicsView_IV_column2)
        self.graphicsView_IV_column3 = PlotWidget(self.tab_IV_rowPlot)
        self.graphicsView_IV_column3.setObjectName(_fromUtf8("graphicsView_IV_column3"))
        self.verticalLayout_32.addWidget(self.graphicsView_IV_column3)
        self.graphicsView_IV_column4 = PlotWidget(self.tab_IV_rowPlot)
        self.graphicsView_IV_column4.setObjectName(_fromUtf8("graphicsView_IV_column4"))
        self.verticalLayout_32.addWidget(self.graphicsView_IV_column4)
        self.horizontalLayout_32.addLayout(self.verticalLayout_32)
        self.tabWidget_rowPlot.addTab(self.tab_IV_rowPlot, _fromUtf8(""))
        self.verticalLayout_rowPlot.addWidget(self.tabWidget_rowPlot)
        self.horizontalLayout_16.addLayout(self.verticalLayout_rowPlot)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_16)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1321, 17))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.toolBar.setFont(font)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtGui.QToolBar(MainWindow)
        self.toolBar_2.setObjectName(_fromUtf8("toolBar_2"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.action_saveState = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/icons/disk--pencil.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_saveState.setIcon(icon1)
        self.action_saveState.setObjectName(_fromUtf8("action_saveState"))
        self.action_loadState = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/icons/folder-open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_loadState.setIcon(icon2)
        self.action_loadState.setObjectName(_fromUtf8("action_loadState"))
        self.action_exit = QtGui.QAction(MainWindow)
        self.action_exit.setMenuRole(QtGui.QAction.QuitRole)
        self.action_exit.setObjectName(_fromUtf8("action_exit"))
        self.action_options = QtGui.QAction(MainWindow)
        self.action_options.setMenuRole(QtGui.QAction.PreferencesRole)
        self.action_options.setObjectName(_fromUtf8("action_options"))
        self.action_enableLivePreview = QtGui.QAction(MainWindow)
        self.action_enableLivePreview.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/icons/control.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_enableLivePreview.setIcon(icon3)
        self.action_enableLivePreview.setObjectName(_fromUtf8("action_enableLivePreview"))
        self.action_enableLogging = QtGui.QAction(MainWindow)
        self.action_enableLogging.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/icons/drive-download.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_enableLogging.setIcon(icon4)
        self.action_enableLogging.setObjectName(_fromUtf8("action_enableLogging"))
        self.action_loadData = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/icons/drive-upload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_loadData.setIcon(icon5)
        self.action_loadData.setObjectName(_fromUtf8("action_loadData"))
        self.action_reset = QtGui.QAction(MainWindow)
        self.action_reset.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/icons/arrow-circle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_reset.setIcon(icon6)
        self.action_reset.setObjectName(_fromUtf8("action_reset"))
        self.action_programFPGAs = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/icons/compile.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_programFPGAs.setIcon(icon7)
        self.action_programFPGAs.setObjectName(_fromUtf8("action_programFPGAs"))
        self.action_capturePlot = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/icons/document-excel-csv.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_capturePlot.setIcon(icon8)
        self.action_capturePlot.setObjectName(_fromUtf8("action_capturePlot"))
        self.action_addVerticalMarker = QtGui.QAction(MainWindow)
        self.action_addVerticalMarker.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/icons/layer-select-point2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_addVerticalMarker.setIcon(icon9)
        self.action_addVerticalMarker.setObjectName(_fromUtf8("action_addVerticalMarker"))
        self.action_addNoiseFit = QtGui.QAction(MainWindow)
        self.action_addNoiseFit.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/icons/layer-shape-curve.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_addNoiseFit.setIcon(icon10)
        self.action_addNoiseFit.setObjectName(_fromUtf8("action_addNoiseFit"))
        self.action_compressData = QtGui.QAction(MainWindow)
        self.action_compressData.setObjectName(_fromUtf8("action_compressData"))
        self.action_enableIV = QtGui.QAction(MainWindow)
        self.action_enableIV.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/icons/application-wave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_enableIV.setIcon(icon11)
        self.action_enableIV.setObjectName(_fromUtf8("action_enableIV"))
        self.menuFile.addAction(self.action_saveState)
        self.menuFile.addAction(self.action_loadState)
        self.menuFile.addAction(self.action_compressData)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_exit)
        self.menuEdit.addAction(self.action_options)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.toolBar.addAction(self.action_saveState)
        self.toolBar.addAction(self.action_loadState)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_programFPGAs)
        self.toolBar.addAction(self.action_enableLivePreview)
        self.toolBar.addAction(self.action_reset)
        self.toolBar.addAction(self.action_enableLogging)
        self.toolBar.addAction(self.action_loadData)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_capturePlot)
        self.toolBar.addAction(self.action_addVerticalMarker)
        self.toolBar.addAction(self.action_addNoiseFit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_enableIV)

        self.retranslateUi(MainWindow)
        self.tabWidget_plot.setCurrentIndex(0)
        self.tabWidget_rowPlot.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "CNP2 User Interface", None))
        self.groupBox_voltageBias_3.setTitle(_translate("MainWindow", "Results", None))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">R</span><span style=\" font-size:10pt; font-weight:600; vertical-align:sub;\">DCFB </span><span style=\" font-size:10pt; font-weight:600;\">(M&Omega;)</span></p></body></html>", None))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">I</span><span style=\" font-size:10pt; font-weight:600; vertical-align:sub;\">DC</span><span style=\" font-size:10pt; font-weight:600;\"> (nA)</span></p></body></html>", None))
        self.label_25.setText(_translate("MainWindow", "Offset:", None))
        self.label_IDCOffset.setText(_translate("MainWindow", "0.0", None))
        self.label_IDCRelative.setText(_translate("MainWindow", "0.0", None))
        self.label_10.setText(_translate("MainWindow", "Net:", None))
        self.label_26.setText(_translate("MainWindow", "Relative:", None))
        self.label_IDCNet.setText(_translate("MainWindow", "0.0", None))
        self.pushButton_IDCSetOffset.setText(_translate("MainWindow", "Zero", None))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">I</span><span style=\" font-size:10pt; font-weight:600; vertical-align:sub;\">RMS</span><span style=\" font-size:10pt; font-weight:600;\"> (pA)</span></p></body></html>", None))
        self.label_12.setText(_translate("MainWindow", "100kHz:", None))
        self.label_100kHzNoise.setText(_translate("MainWindow", "0.0", None))
        self.label_13.setText(_translate("MainWindow", "1MHz:", None))
        self.label_1MHzNoise.setText(_translate("MainWindow", "0.0", None))
        self.label_16.setText(_translate("MainWindow", "10MHz:", None))
        self.label_10MHzNoise.setText(_translate("MainWindow", "0.0", None))
        self.groupBox_voltageBias_2.setTitle(_translate("MainWindow", "Control/Status", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "ADC Control", None))
        self.checkBox_ADC0enable.setText(_translate("MainWindow", "ADC 0", None))
        self.checkBox_ADCenable.setText(_translate("MainWindow", "Enable all", None))
        self.checkBox_ADC2enable.setText(_translate("MainWindow", "ADC 2", None))
        self.checkBox_ADC4enable.setText(_translate("MainWindow", "ADC 4", None))
        self.checkBox_ADC1enable.setText(_translate("MainWindow", "ADC 1", None))
        self.checkBox_ADC3enable.setText(_translate("MainWindow", "ADC 3", None))
        self.pushButton_getDataFileSelect.setText(_translate("MainWindow", "...", None))
        self.label_3.setText(_translate("MainWindow", "  Column select:", None))
        self.comboBox_rowSelect.setItemText(0, _translate("MainWindow", "Row 0", None))
        self.comboBox_rowSelect.setItemText(1, _translate("MainWindow", "Row 1", None))
        self.comboBox_rowSelect.setItemText(2, _translate("MainWindow", "Row 2", None))
        self.comboBox_rowSelect.setItemText(3, _translate("MainWindow", "Row 3", None))
        self.comboBox_rowSelect.setItemText(4, _translate("MainWindow", "Row 4 (SWCap)", None))
        self.comboBox_amplifierGainSelect.setItemText(0, _translate("MainWindow", "0.05pF", None))
        self.comboBox_amplifierGainSelect.setItemText(1, _translate("MainWindow", "0.15pF", None))
        self.comboBox_amplifierGainSelect.setItemText(2, _translate("MainWindow", "0.9pF", None))
        self.comboBox_amplifierGainSelect.setItemText(3, _translate("MainWindow", "1pF", None))
        self.label_4.setText(_translate("MainWindow", " Amplifier Gain:", None))
        self.comboBox_columnSelect.setItemText(0, _translate("MainWindow", "Column 0", None))
        self.comboBox_columnSelect.setItemText(1, _translate("MainWindow", "Column 1", None))
        self.comboBox_columnSelect.setItemText(2, _translate("MainWindow", "Column 2", None))
        self.comboBox_columnSelect.setItemText(3, _translate("MainWindow", "Column 3", None))
        self.comboBox_columnSelect.setItemText(4, _translate("MainWindow", "Column 4", None))
        self.label_2.setText(_translate("MainWindow", "Row select:", None))
        self.pushButton_programChip.setText(_translate("MainWindow", "Program chip", None))
        self.checkBox_biasEnable.setText(_translate("MainWindow", "Enable bias", None))
        self.checkBox_integratorReset.setText(_translate("MainWindow", "Reset integrator", None))
        self.checkBox_connectElectrode.setText(_translate("MainWindow", "Connect electrode", None))
        self.checkBox_connectISRCEXT.setText(_translate("MainWindow", "Connect ISRCEXT", None))
        self.checkBox_enableSwitchedCapClock.setText(_translate("MainWindow", "Enable SWCap clock", None))
        self.checkBox_frequencyResponse.setText(_translate("MainWindow", "Frequency response mode", None))
        self.checkBox_enableTriangleWave.setText(_translate("MainWindow", "Triangle wave", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Pore Char.", None))
        self.checkBox_enableSquareWave.setText(_translate("MainWindow", "Measure", None))
        self.label_poreResistance_name.setText(_translate("MainWindow", "<html><head/><body><p>R<span style=\" vertical-align:sub;\">pore</span>:</p></body></html>", None))
        self.label_poreResistance.setText(_translate("MainWindow", "0.0", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Filtering", None))
        self.checkBox_enableLivePreviewFilter.setText(_translate("MainWindow", "Enable filter", None))
        self.label_20.setText(_translate("MainWindow", "kHz", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "FPGA Status", None))
        self.label_28.setText(_translate("MainWindow", "RAM Usage", None))
        self.label_27.setText(_translate("MainWindow", "Active", None))
        self.label_FPGASlaveBufferUtilization.setText(_translate("MainWindow", "0.0/128 MB", None))
        self.label_9.setText(_translate("MainWindow", "Slave:", None))
        self.label.setText(_translate("MainWindow", "Master:", None))
        self.label_FPGAMasterBufferUtilization.setText(_translate("MainWindow", "0.0/128 MB", None))
        self.groupBox_voltageBias.setTitle(_translate("MainWindow", "Voltage Bias", None))
        self.label_8.setText(_translate("MainWindow", "mV", None))
        self.groupBox.setTitle(_translate("MainWindow", "Absolute", None))
        self.pushButton_counterelectrodePotentialZero_absolute.setText(_translate("MainWindow", "Zero", None))
        self.pushButton_counterelectrodePotentialPlus900_absolute.setText(_translate("MainWindow", "+900mV", None))
        self.pushButton_counterelectrodePotentialPlus500_absolute.setText(_translate("MainWindow", "+500mV", None))
        self.pushButton_counterelectrodePotentialPlus400_absolute.setText(_translate("MainWindow", "+400mV", None))
        self.pushButton_counterelectrodePotentialPlus300_absolute.setText(_translate("MainWindow", "+300mV", None))
        self.pushButton_counterelectrodePotentialPlus200_absolute.setText(_translate("MainWindow", "+200mV", None))
        self.pushButton_counterelectrodePotentialPlus100_absolute.setText(_translate("MainWindow", "+100mV", None))
        self.pushButton_counterelectrodePotentialPlus50_absolute.setText(_translate("MainWindow", "+50mV", None))
        self.pushButton_counterelectrodePotentialMinus900_absolute.setText(_translate("MainWindow", "-900mV", None))
        self.pushButton_counterelectrodePotentialMinus500_absolute.setText(_translate("MainWindow", "-500mV", None))
        self.pushButton_counterelectrodePotentialMinus400_absolute.setText(_translate("MainWindow", "-400mV", None))
        self.pushButton_counterelectrodePotentialMinus300_absolute.setText(_translate("MainWindow", "-300mV", None))
        self.pushButton_counterelectrodePotentialMinus200_absolute.setText(_translate("MainWindow", "-200mV", None))
        self.pushButton_counterelectrodePotentialMinus100_absolute.setText(_translate("MainWindow", "-100mV", None))
        self.pushButton_counterelectrodePotentialMinus50_absolute.setText(_translate("MainWindow", "-50mV", None))
        self.groupBox1.setTitle(_translate("MainWindow", "Relative", None))
        self.pushButton_counterelectrodePotentialMinus10_relative.setText(_translate("MainWindow", "-10mV", None))
        self.pushButton_counterelectrodePotentialPlus10_relative.setText(_translate("MainWindow", "+10mV", None))
        self.pushButton_counterelectrodePotentialPlus100_relative.setText(_translate("MainWindow", "+100mV", None))
        self.pushButton_counterelectrodePotentialMinus50_relative.setText(_translate("MainWindow", "-50mV", None))
        self.pushButton_counterelectrodePotentialMinus100_relative.setText(_translate("MainWindow", "-100mV", None))
        self.pushButton_counterelectrodePotentialPlus50_relative.setText(_translate("MainWindow", "+50mV", None))
        self.label_7.setText(_translate("MainWindow", "Log Duration (s):", None))
        self.tabWidget_plot.setTabText(self.tabWidget_plot.indexOf(self.tab_time), _translate("MainWindow", "Time", None))
        self.tabWidget_plot.setTabText(self.tabWidget_plot.indexOf(self.tab_frequency), _translate("MainWindow", "Frequency", None))
        self.tabWidget_plot.setTabText(self.tabWidget_plot.indexOf(self.tab_histogram), _translate("MainWindow", "Histogram", None))
        self.tabWidget_plot.setTabText(self.tabWidget_plot.indexOf(self.tab_IV), _translate("MainWindow", "I-V", None))
        self.checkBox_rowPlot_enable.setText(_translate("MainWindow", "Enable", None))
        self.label_rowPlot_rowSelect_label.setText(_translate("MainWindow", "Row Select", None))
        self.comboBox_rowSelect_2.setItemText(0, _translate("MainWindow", "Row 0", None))
        self.comboBox_rowSelect_2.setItemText(1, _translate("MainWindow", "Row 1", None))
        self.comboBox_rowSelect_2.setItemText(2, _translate("MainWindow", "Row 2", None))
        self.comboBox_rowSelect_2.setItemText(3, _translate("MainWindow", "Row 3", None))
        self.comboBox_rowSelect_2.setItemText(4, _translate("MainWindow", "Row 4 (SWCap)", None))
        self.label_rowPlot_logDuration.setText(_translate("MainWindow", "Log Duration (s):", None))
        self.tabWidget_rowPlot.setTabText(self.tabWidget_rowPlot.indexOf(self.tab_time_rowPlot), _translate("MainWindow", "Time", None))
        self.tabWidget_rowPlot.setTabText(self.tabWidget_rowPlot.indexOf(self.tab_frequency_rowPlot), _translate("MainWindow", "Frequency", None))
        self.tabWidget_rowPlot.setTabText(self.tabWidget_rowPlot.indexOf(self.tab_histogram_rowPlot), _translate("MainWindow", "Histogram", None))
        self.tabWidget_rowPlot.setTabText(self.tabWidget_rowPlot.indexOf(self.tab_IV_rowPlot), _translate("MainWindow", "I-V", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2", None))
        self.action_saveState.setText(_translate("MainWindow", "Save state", None))
        self.action_saveState.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.action_loadState.setText(_translate("MainWindow", "Load state", None))
        self.action_loadState.setShortcut(_translate("MainWindow", "Ctrl+L", None))
        self.action_exit.setText(_translate("MainWindow", "Exit", None))
        self.action_exit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.action_options.setText(_translate("MainWindow", "Options", None))
        self.action_options.setShortcut(_translate("MainWindow", "Ctrl+P", None))
        self.action_enableLivePreview.setText(_translate("MainWindow", "Start preview", None))
        self.action_enableLivePreview.setToolTip(_translate("MainWindow", "Enables live preview of the data", None))
        self.action_enableLogging.setText(_translate("MainWindow", "Start logging", None))
        self.action_enableLogging.setToolTip(_translate("MainWindow", "Start logging the data being displayed", None))
        self.action_loadData.setText(_translate("MainWindow", "Load data", None))
        self.action_loadData.setToolTip(_translate("MainWindow", "Load previously saved binary data", None))
        self.action_reset.setText(_translate("MainWindow", "Reset system", None))
        self.action_reset.setToolTip(_translate("MainWindow", "Resets the system", None))
        self.action_programFPGAs.setText(_translate("MainWindow", "Program FPGAs", None))
        self.action_programFPGAs.setToolTip(_translate("MainWindow", "Reprogram the FPGAs using existing bitfiles", None))
        self.action_capturePlot.setText(_translate("MainWindow", "Capture plot", None))
        self.action_capturePlot.setToolTip(_translate("MainWindow", "Saves currently displayed plot as a csv file", None))
        self.action_addVerticalMarker.setText(_translate("MainWindow", "Add a vertical marker", None))
        self.action_addVerticalMarker.setToolTip(_translate("MainWindow", "Adds a vertical marker to the current plot", None))
        self.action_addNoiseFit.setText(_translate("MainWindow", "Add fit to the noise plot", None))
        self.action_addNoiseFit.setToolTip(_translate("MainWindow", "Adds a polynomial fit to the noise spectrum", None))
        self.action_compressData.setText(_translate("MainWindow", "Compress data", None))
        self.action_enableIV.setText(_translate("MainWindow", "Enable IV", None))
        self.action_enableIV.setToolTip(_translate("MainWindow", "Starts the I-V function", None))

from pyqtgraph import PlotWidget
