# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/loadOldData.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(682, 654)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 26, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem1)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setSpacing(3)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_12.addWidget(self.label_14)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.lineEdit_RDCFB = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lineEdit_RDCFB.sizePolicy().hasHeightForWidth())
        self.lineEdit_RDCFB.setSizePolicy(sizePolicy)
        self.lineEdit_RDCFB.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_RDCFB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_RDCFB.setObjectName(_fromUtf8("lineEdit_RDCFB"))
        self.horizontalLayout_14.addWidget(self.lineEdit_RDCFB)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem4)
        self.label_24 = QtGui.QLabel(self.centralwidget)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_26.addWidget(self.label_24)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem5)
        self.verticalLayout_22.addLayout(self.horizontalLayout_26)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_25 = QtGui.QLabel(self.centralwidget)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_9.addWidget(self.label_25, 0, 0, 1, 1)
        self.label_IDCOffset = QtGui.QLabel(self.centralwidget)
        self.label_IDCOffset.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_IDCOffset.setObjectName(_fromUtf8("label_IDCOffset"))
        self.gridLayout_9.addWidget(self.label_IDCOffset, 0, 1, 1, 1)
        self.label_IDCRelative = QtGui.QLabel(self.centralwidget)
        self.label_IDCRelative.setMinimumSize(QtCore.QSize(0, 15))
        self.label_IDCRelative.setObjectName(_fromUtf8("label_IDCRelative"))
        self.gridLayout_9.addWidget(self.label_IDCRelative, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_9.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.centralwidget)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_9.addWidget(self.label_26, 1, 0, 1, 1)
        self.label_IDCNet = QtGui.QLabel(self.centralwidget)
        self.label_IDCNet.setMinimumSize(QtCore.QSize(0, 15))
        self.label_IDCNet.setObjectName(_fromUtf8("label_IDCNet"))
        self.gridLayout_9.addWidget(self.label_IDCNet, 2, 1, 1, 1)
        self.pushButton_IDCSetOffset = QtGui.QPushButton(self.centralwidget)
        self.pushButton_IDCSetOffset.setMinimumSize(QtCore.QSize(30, 0))
        self.pushButton_IDCSetOffset.setMaximumSize(QtCore.QSize(40, 20))
        self.pushButton_IDCSetOffset.setObjectName(_fromUtf8("pushButton_IDCSetOffset"))
        self.gridLayout_9.addWidget(self.pushButton_IDCSetOffset, 0, 2, 1, 1)
        self.verticalLayout_22.addLayout(self.gridLayout_9)
        self.verticalLayout_11.addLayout(self.verticalLayout_22)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_13.addWidget(self.label_11)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_8.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_100kHzNoise = QtGui.QLabel(self.centralwidget)
        self.label_100kHzNoise.setObjectName(_fromUtf8("label_100kHzNoise"))
        self.gridLayout_8.addWidget(self.label_100kHzNoise, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_8.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_1MHzNoise = QtGui.QLabel(self.centralwidget)
        self.label_1MHzNoise.setObjectName(_fromUtf8("label_1MHzNoise"))
        self.gridLayout_8.addWidget(self.label_1MHzNoise, 1, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_8.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_10MHzNoise = QtGui.QLabel(self.centralwidget)
        self.label_10MHzNoise.setObjectName(_fromUtf8("label_10MHzNoise"))
        self.gridLayout_8.addWidget(self.label_10MHzNoise, 2, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_8)
        self.verticalLayout_11.addLayout(self.verticalLayout_9)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setMinimumSize(QtCore.QSize(0, 16))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_3.addWidget(self.label_19)
        self.checkBox_enableLivePreviewFilter = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_enableLivePreviewFilter.setMaximumSize(QtCore.QSize(16777215, 17))
        self.checkBox_enableLivePreviewFilter.setObjectName(_fromUtf8("checkBox_enableLivePreviewFilter"))
        self.verticalLayout_3.addWidget(self.checkBox_enableLivePreviewFilter, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lineEdit_livePreviewFilterBandwidth = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_livePreviewFilterBandwidth.setMaximumSize(QtCore.QSize(56, 20))
        self.lineEdit_livePreviewFilterBandwidth.setText(_fromUtf8(""))
        self.lineEdit_livePreviewFilterBandwidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_livePreviewFilterBandwidth.setObjectName(_fromUtf8("lineEdit_livePreviewFilterBandwidth"))
        self.horizontalLayout_6.addWidget(self.lineEdit_livePreviewFilterBandwidth)
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setMaximumSize(QtCore.QSize(31, 20))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_6.addWidget(self.label_20)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout_11.addLayout(self.verticalLayout_3)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setSpacing(3)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_10.addLayout(self.gridLayout_6)
        self.checkBox_enableWaveletDenoising = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_enableWaveletDenoising.setObjectName(_fromUtf8("checkBox_enableWaveletDenoising"))
        self.verticalLayout_10.addWidget(self.checkBox_enableWaveletDenoising, QtCore.Qt.AlignHCenter)
        self.lineEdit_motherWavelet = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_motherWavelet.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_motherWavelet.setObjectName(_fromUtf8("lineEdit_motherWavelet"))
        self.verticalLayout_10.addWidget(self.lineEdit_motherWavelet)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.verticalLayout_13.addLayout(self.verticalLayout_11)
        self.verticalLayout_20.addLayout(self.verticalLayout_13)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_20)
        self.tabWidget_plot = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_plot.setEnabled(True)
        self.tabWidget_plot.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget_plot.setDocumentMode(False)
        self.tabWidget_plot.setObjectName(_fromUtf8("tabWidget_plot"))
        self.tab_time = QtGui.QWidget()
        self.tab_time.setObjectName(_fromUtf8("tab_time"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_time)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.graphicsView_time = PlotWidget(self.tab_time)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_time.sizePolicy().hasHeightForWidth())
        self.graphicsView_time.setSizePolicy(sizePolicy)
        self.graphicsView_time.setMinimumSize(QtCore.QSize(400, 300))
        self.graphicsView_time.setObjectName(_fromUtf8("graphicsView_time"))
        self.horizontalLayout_2.addWidget(self.graphicsView_time)
        self.tabWidget_plot.addTab(self.tab_time, _fromUtf8(""))
        self.tab_frequency = QtGui.QWidget()
        self.tab_frequency.setObjectName(_fromUtf8("tab_frequency"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_frequency)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.graphicsView_frequency = PlotWidget(self.tab_frequency)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_frequency.sizePolicy().hasHeightForWidth())
        self.graphicsView_frequency.setSizePolicy(sizePolicy)
        self.graphicsView_frequency.setMinimumSize(QtCore.QSize(400, 300))
        self.graphicsView_frequency.setObjectName(_fromUtf8("graphicsView_frequency"))
        self.horizontalLayout_3.addWidget(self.graphicsView_frequency)
        self.tabWidget_plot.addTab(self.tab_frequency, _fromUtf8(""))
        self.tab_histogram = QtGui.QWidget()
        self.tab_histogram.setObjectName(_fromUtf8("tab_histogram"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_histogram)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.graphicsView_histogram = PlotWidget(self.tab_histogram)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_histogram.sizePolicy().hasHeightForWidth())
        self.graphicsView_histogram.setSizePolicy(sizePolicy)
        self.graphicsView_histogram.setMinimumSize(QtCore.QSize(400, 300))
        self.graphicsView_histogram.setObjectName(_fromUtf8("graphicsView_histogram"))
        self.horizontalLayout_4.addWidget(self.graphicsView_histogram)
        self.tabWidget_plot.addTab(self.tab_histogram, _fromUtf8(""))
        self.tab_eventViewer = QtGui.QWidget()
        self.tab_eventViewer.setObjectName(_fromUtf8("tab_eventViewer"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tab_eventViewer)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.graphicsView_eventViewer = PlotWidget(self.tab_eventViewer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_eventViewer.sizePolicy().hasHeightForWidth())
        self.graphicsView_eventViewer.setSizePolicy(sizePolicy)
        self.graphicsView_eventViewer.setMinimumSize(QtCore.QSize(400, 300))
        self.graphicsView_eventViewer.setObjectName(_fromUtf8("graphicsView_eventViewer"))
        self.horizontalLayout_8.addWidget(self.graphicsView_eventViewer)
        self.tabWidget_plot.addTab(self.tab_eventViewer, _fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.tabWidget_plot)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.pushButton_previousEvent = QtGui.QPushButton(self.centralwidget)
        self.pushButton_previousEvent.setEnabled(False)
        self.pushButton_previousEvent.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("ui/Icons/icons/arrow-180.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_previousEvent.setIcon(icon)
        self.pushButton_previousEvent.setObjectName(_fromUtf8("pushButton_previousEvent"))
        self.horizontalLayout.addWidget(self.pushButton_previousEvent)
        self.lineEdit_currentEvent = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_currentEvent.setEnabled(False)
        self.lineEdit_currentEvent.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_currentEvent.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_currentEvent.setObjectName(_fromUtf8("lineEdit_currentEvent"))
        self.horizontalLayout.addWidget(self.lineEdit_currentEvent)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_totalEvents = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_totalEvents.setEnabled(False)
        self.lineEdit_totalEvents.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_totalEvents.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_totalEvents.setReadOnly(True)
        self.lineEdit_totalEvents.setObjectName(_fromUtf8("lineEdit_totalEvents"))
        self.horizontalLayout.addWidget(self.lineEdit_totalEvents)
        self.pushButton_nextEvent = QtGui.QPushButton(self.centralwidget)
        self.pushButton_nextEvent.setEnabled(False)
        self.pushButton_nextEvent.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("ui/Icons/icons/arrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_nextEvent.setIcon(icon1)
        self.pushButton_nextEvent.setObjectName(_fromUtf8("pushButton_nextEvent"))
        self.horizontalLayout.addWidget(self.pushButton_nextEvent)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.comboBox_columnSelect = QtGui.QComboBox(self.centralwidget)
        self.comboBox_columnSelect.setObjectName(_fromUtf8("comboBox_columnSelect"))
        self.comboBox_columnSelect.addItem(_fromUtf8(""))
        self.comboBox_columnSelect.addItem(_fromUtf8(""))
        self.comboBox_columnSelect.addItem(_fromUtf8(""))
        self.comboBox_columnSelect.addItem(_fromUtf8(""))
        self.comboBox_columnSelect.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.comboBox_columnSelect)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_7.addWidget(self.label)
        self.lineEdit_minimumEventDuration = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_minimumEventDuration.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_minimumEventDuration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_minimumEventDuration.setObjectName(_fromUtf8("lineEdit_minimumEventDuration"))
        self.horizontalLayout_7.addWidget(self.lineEdit_minimumEventDuration)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_7.addWidget(self.label_2)
        self.lineEdit_maximumEventDuration = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_maximumEventDuration.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_maximumEventDuration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_maximumEventDuration.setObjectName(_fromUtf8("lineEdit_maximumEventDuration"))
        self.horizontalLayout_7.addWidget(self.lineEdit_maximumEventDuration)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_7.addWidget(self.label_3)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.lineEdit_threshold = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_threshold.setEnabled(True)
        self.lineEdit_threshold.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_threshold.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_threshold.setObjectName(_fromUtf8("lineEdit_threshold"))
        self.horizontalLayout_7.addWidget(self.lineEdit_threshold)
        self.comboBox_thresholdUnitsSelect = QtGui.QComboBox(self.centralwidget)
        self.comboBox_thresholdUnitsSelect.setEnabled(True)
        self.comboBox_thresholdUnitsSelect.setMaximumSize(QtCore.QSize(40, 16777215))
        self.comboBox_thresholdUnitsSelect.setObjectName(_fromUtf8("comboBox_thresholdUnitsSelect"))
        self.comboBox_thresholdUnitsSelect.addItem(_fromUtf8(""))
        self.comboBox_thresholdUnitsSelect.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.comboBox_thresholdUnitsSelect)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.checkBox_enableCUSUM = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_enableCUSUM.setMaximumSize(QtCore.QSize(16777215, 20))
        self.checkBox_enableCUSUM.setObjectName(_fromUtf8("checkBox_enableCUSUM"))
        self.horizontalLayout_10.addWidget(self.checkBox_enableCUSUM)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_10.addWidget(self.label_15)
        self.lineEdit_CUSUMDelta = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_CUSUMDelta.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_CUSUMDelta.sizePolicy().hasHeightForWidth())
        self.lineEdit_CUSUMDelta.setSizePolicy(sizePolicy)
        self.lineEdit_CUSUMDelta.setMaximumSize(QtCore.QSize(50, 20))
        self.lineEdit_CUSUMDelta.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_CUSUMDelta.setReadOnly(False)
        self.lineEdit_CUSUMDelta.setObjectName(_fromUtf8("lineEdit_CUSUMDelta"))
        self.horizontalLayout_10.addWidget(self.lineEdit_CUSUMDelta)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_10.addWidget(self.label_5)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem14)
        self.pushButton_analyzeData = QtGui.QPushButton(self.centralwidget)
        self.pushButton_analyzeData.setObjectName(_fromUtf8("pushButton_analyzeData"))
        self.horizontalLayout_10.addWidget(self.pushButton_analyzeData)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.comboBox_histogramModeSelect = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_histogramModeSelect.sizePolicy().hasHeightForWidth())
        self.comboBox_histogramModeSelect.setSizePolicy(sizePolicy)
        self.comboBox_histogramModeSelect.setObjectName(_fromUtf8("comboBox_histogramModeSelect"))
        self.comboBox_histogramModeSelect.addItem(_fromUtf8(""))
        self.comboBox_histogramModeSelect.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.comboBox_histogramModeSelect)
        self.checkBox_enableIonChannelMode = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_enableIonChannelMode.setObjectName(_fromUtf8("checkBox_enableIonChannelMode"))
        self.horizontalLayout_12.addWidget(self.checkBox_enableIonChannelMode)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        spacerItem16 = QtGui.QSpacerItem(20, 44, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem16)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 682, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menu_export = QtGui.QMenu(self.menubar)
        self.menu_export.setObjectName(_fromUtf8("menu_export"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_loadData = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("ui/Icons/icons/folder-open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_loadData.setIcon(icon2)
        self.action_loadData.setObjectName(_fromUtf8("action_loadData"))
        self.action_options = QtGui.QAction(MainWindow)
        self.action_options.setObjectName(_fromUtf8("action_options"))
        self.action_exit = QtGui.QAction(MainWindow)
        self.action_exit.setObjectName(_fromUtf8("action_exit"))
        self.action_capturePlot = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("ui/Icons/icons/document-excel-csv.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_capturePlot.setIcon(icon3)
        self.action_capturePlot.setObjectName(_fromUtf8("action_capturePlot"))
        self.action_addVerticalMarker = QtGui.QAction(MainWindow)
        self.action_addVerticalMarker.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("ui/Icons/icons/layer-select-point2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_addVerticalMarker.setIcon(icon4)
        self.action_addVerticalMarker.setObjectName(_fromUtf8("action_addVerticalMarker"))
        self.action_addNoiseFit = QtGui.QAction(MainWindow)
        self.action_addNoiseFit.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("ui/Icons/icons/layer-shape-curve.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_addNoiseFit.setIcon(icon5)
        self.action_addNoiseFit.setObjectName(_fromUtf8("action_addNoiseFit"))
        self.action_nextFile = QtGui.QAction(MainWindow)
        self.action_nextFile.setIcon(icon1)
        self.action_nextFile.setObjectName(_fromUtf8("action_nextFile"))
        self.action_previousFile = QtGui.QAction(MainWindow)
        self.action_previousFile.setIcon(icon)
        self.action_previousFile.setObjectName(_fromUtf8("action_previousFile"))
        self.action_deleteFile = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("ui/Icons/icons/cross.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_deleteFile.setIcon(icon6)
        self.action_deleteFile.setObjectName(_fromUtf8("action_deleteFile"))
        self.action_exportAllEventsAsCSV = QtGui.QAction(MainWindow)
        self.action_exportAllEventsAsCSV.setEnabled(False)
        self.action_exportAllEventsAsCSV.setObjectName(_fromUtf8("action_exportAllEventsAsCSV"))
        self.menuFile.addAction(self.action_loadData)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_exit)
        self.menuEdit.addAction(self.action_options)
        self.menu_export.addAction(self.action_exportAllEventsAsCSV)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menu_export.menuAction())
        self.toolBar.addAction(self.action_loadData)
        self.toolBar.addAction(self.action_previousFile)
        self.toolBar.addAction(self.action_nextFile)
        self.toolBar.addAction(self.action_deleteFile)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_capturePlot)
        self.toolBar.addAction(self.action_addVerticalMarker)
        self.toolBar.addAction(self.action_addNoiseFit)

        self.retranslateUi(MainWindow)
        self.tabWidget_plot.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">R</span><span style=\" font-size:10pt; font-weight:600; vertical-align:sub;\">DCFB </span><span style=\" font-size:10pt; font-weight:600;\">(M&Omega;)</span></p></body></html>", None))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">I</span><span style=\" font-size:10pt; font-weight:600; vertical-align:sub;\">DC</span><span style=\" font-size:10pt; font-weight:600;\"> (nA)</span></p></body></html>", None))
        self.label_25.setText(_translate("MainWindow", "Offset:", None))
        self.label_IDCOffset.setText(_translate("MainWindow", "0.0", None))
        self.label_IDCRelative.setText(_translate("MainWindow", "0.0", None))
        self.label_10.setText(_translate("MainWindow", "Net:", None))
        self.label_26.setText(_translate("MainWindow", "Relative:", None))
        self.label_IDCNet.setText(_translate("MainWindow", "0.0", None))
        self.pushButton_IDCSetOffset.setText(_translate("MainWindow", "Zero", None))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">I</span><span style=\" font-size:10pt; font-weight:600; vertical-align:sub;\">RMS</span><span style=\" font-size:10pt; font-weight:600;\"> (pA)</span></p></body></html>", None))
        self.label_12.setText(_translate("MainWindow", "100kHz:", None))
        self.label_100kHzNoise.setText(_translate("MainWindow", "0.0", None))
        self.label_13.setText(_translate("MainWindow", "1MHz:", None))
        self.label_1MHzNoise.setText(_translate("MainWindow", "0.0", None))
        self.label_16.setText(_translate("MainWindow", "10MHz:", None))
        self.label_10MHzNoise.setText(_translate("MainWindow", "0.0", None))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Filtering</span></p></body></html>", None))
        self.checkBox_enableLivePreviewFilter.setText(_translate("MainWindow", "Enable filter", None))
        self.label_20.setText(_translate("MainWindow", "kHz", None))
        self.checkBox_enableWaveletDenoising.setText(_translate("MainWindow", "Enable wavelet denoising", None))
        self.lineEdit_motherWavelet.setText(_translate("MainWindow", "bior3.9", None))
        self.tabWidget_plot.setTabText(self.tabWidget_plot.indexOf(self.tab_time), _translate("MainWindow", "Time", None))
        self.tabWidget_plot.setTabText(self.tabWidget_plot.indexOf(self.tab_frequency), _translate("MainWindow", "Frequency", None))
        self.tabWidget_plot.setTabText(self.tabWidget_plot.indexOf(self.tab_histogram), _translate("MainWindow", "Histogram", None))
        self.tabWidget_plot.setTabText(self.tabWidget_plot.indexOf(self.tab_eventViewer), _translate("MainWindow", "Event Viewer", None))
        self.lineEdit_currentEvent.setText(_translate("MainWindow", "0", None))
        self.label_4.setText(_translate("MainWindow", "of", None))
        self.lineEdit_totalEvents.setText(_translate("MainWindow", "0", None))
        self.comboBox_columnSelect.setItemText(0, _translate("MainWindow", "Column 0", None))
        self.comboBox_columnSelect.setItemText(1, _translate("MainWindow", "Column 1", None))
        self.comboBox_columnSelect.setItemText(2, _translate("MainWindow", "Column 2", None))
        self.comboBox_columnSelect.setItemText(3, _translate("MainWindow", "Column 3", None))
        self.comboBox_columnSelect.setItemText(4, _translate("MainWindow", "Column 4", None))
        self.label.setText(_translate("MainWindow", "Event duration:", None))
        self.lineEdit_minimumEventDuration.setText(_translate("MainWindow", "1", None))
        self.label_2.setText(_translate("MainWindow", "us to", None))
        self.lineEdit_maximumEventDuration.setText(_translate("MainWindow", "1000", None))
        self.label_3.setText(_translate("MainWindow", "us", None))
        self.label_6.setText(_translate("MainWindow", "Threshold:", None))
        self.lineEdit_threshold.setText(_translate("MainWindow", "5", None))
        self.comboBox_thresholdUnitsSelect.setItemText(0, _translate("MainWindow", "σ\'s", None))
        self.comboBox_thresholdUnitsSelect.setItemText(1, _translate("MainWindow", "nA", None))
        self.checkBox_enableCUSUM.setText(_translate("MainWindow", "CUSUM", None))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Δ</span><span style=\" font-size:10pt; vertical-align:sub;\">CUSUM </span><span style=\" font-size:10pt;\">:</span></p></body></html>", None))
        self.lineEdit_CUSUMDelta.setText(_translate("MainWindow", "1", None))
        self.label_5.setText(_translate("MainWindow", "nA", None))
        self.pushButton_analyzeData.setText(_translate("MainWindow", "Analyze data", None))
        self.comboBox_histogramModeSelect.setItemText(0, _translate("MainWindow", "Mean current block vs dwell time", None))
        self.comboBox_histogramModeSelect.setItemText(1, _translate("MainWindow", "Current block level vs count", None))
        self.checkBox_enableIonChannelMode.setText(_translate("MainWindow", "Ion channel mode", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menu_export.setTitle(_translate("MainWindow", "E&xport", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.action_loadData.setText(_translate("MainWindow", "Load data", None))
        self.action_loadData.setShortcut(_translate("MainWindow", "Ctrl+L", None))
        self.action_options.setText(_translate("MainWindow", "Options", None))
        self.action_options.setShortcut(_translate("MainWindow", "Ctrl+P", None))
        self.action_exit.setText(_translate("MainWindow", "Exit", None))
        self.action_exit.setShortcut(_translate("MainWindow", "Ctrl+W", None))
        self.action_capturePlot.setText(_translate("MainWindow", "Capture plot", None))
        self.action_capturePlot.setToolTip(_translate("MainWindow", "Saves currently displayed plot as a csv file", None))
        self.action_addVerticalMarker.setText(_translate("MainWindow", "Add a vertical marker", None))
        self.action_addVerticalMarker.setToolTip(_translate("MainWindow", "Adds a vertical marker to the current plot", None))
        self.action_addNoiseFit.setText(_translate("MainWindow", "Add fit to the noise plot", None))
        self.action_addNoiseFit.setToolTip(_translate("MainWindow", "Adds a polynomial fit to the noise spectrum", None))
        self.action_nextFile.setText(_translate("MainWindow", "Next file", None))
        self.action_nextFile.setToolTip(_translate("MainWindow", "Load the next file in the directory", None))
        self.action_previousFile.setText(_translate("MainWindow", "Previous file", None))
        self.action_previousFile.setToolTip(_translate("MainWindow", "Load previous file in the directory", None))
        self.action_deleteFile.setText(_translate("MainWindow", "Delete file", None))
        self.action_deleteFile.setToolTip(_translate("MainWindow", "Delete current file", None))
        self.action_exportAllEventsAsCSV.setText(_translate("MainWindow", "All events as CSV", None))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

