# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\plotWindow.ui'
#
# Created: Wed Feb 18 15:34:55 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(598, 597)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 26, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.tabWidget_plot = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_plot.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget_plot.setObjectName(_fromUtf8("tabWidget_plot"))
        self.tab_time = QtGui.QWidget()
        self.tab_time.setObjectName(_fromUtf8("tab_time"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_time)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.graphicsView_time = PlotWidget(self.tab_time)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_time.sizePolicy().hasHeightForWidth())
        self.graphicsView_time.setSizePolicy(sizePolicy)
        self.graphicsView_time.setMinimumSize(QtCore.QSize(400, 300))
        self.graphicsView_time.setObjectName(_fromUtf8("graphicsView_time"))
        self.horizontalLayout_2.addWidget(self.graphicsView_time)
        self.tabWidget_plot.addTab(self.tab_time, _fromUtf8(""))
        self.tab_frequency = QtGui.QWidget()
        self.tab_frequency.setObjectName(_fromUtf8("tab_frequency"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_frequency)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.graphicsView_frequency = PlotWidget(self.tab_frequency)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_frequency.sizePolicy().hasHeightForWidth())
        self.graphicsView_frequency.setSizePolicy(sizePolicy)
        self.graphicsView_frequency.setMinimumSize(QtCore.QSize(400, 300))
        self.graphicsView_frequency.setObjectName(_fromUtf8("graphicsView_frequency"))
        self.horizontalLayout_3.addWidget(self.graphicsView_frequency)
        self.tabWidget_plot.addTab(self.tab_frequency, _fromUtf8(""))
        self.tab_histogram = QtGui.QWidget()
        self.tab_histogram.setObjectName(_fromUtf8("tab_histogram"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_histogram)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.graphicsView_histogram = PlotWidget(self.tab_histogram)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_histogram.sizePolicy().hasHeightForWidth())
        self.graphicsView_histogram.setSizePolicy(sizePolicy)
        self.graphicsView_histogram.setMinimumSize(QtCore.QSize(400, 300))
        self.graphicsView_histogram.setObjectName(_fromUtf8("graphicsView_histogram"))
        self.horizontalLayout_4.addWidget(self.graphicsView_histogram)
        self.tabWidget_plot.addTab(self.tab_histogram, _fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.tabWidget_plot)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton_loadData = QtGui.QPushButton(self.centralwidget)
        self.pushButton_loadData.setObjectName(_fromUtf8("pushButton_loadData"))
        self.horizontalLayout.addWidget(self.pushButton_loadData)
        self.comboBox_columnSelect = QtGui.QComboBox(self.centralwidget)
        self.comboBox_columnSelect.setObjectName(_fromUtf8("comboBox_columnSelect"))
        self.comboBox_columnSelect.addItem(_fromUtf8(""))
        self.comboBox_columnSelect.addItem(_fromUtf8(""))
        self.comboBox_columnSelect.addItem(_fromUtf8(""))
        self.comboBox_columnSelect.addItem(_fromUtf8(""))
        self.comboBox_columnSelect.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox_columnSelect)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalSlider = QtGui.QSlider(self.centralwidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(10)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.horizontalScrollBar = QtGui.QScrollBar(self.centralwidget)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName(_fromUtf8("horizontalScrollBar"))
        self.verticalLayout.addWidget(self.horizontalScrollBar)
        spacerItem5 = QtGui.QSpacerItem(20, 44, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 598, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_loadData = QtGui.QAction(MainWindow)
        self.action_loadData.setObjectName(_fromUtf8("action_loadData"))
        self.action_options = QtGui.QAction(MainWindow)
        self.action_options.setObjectName(_fromUtf8("action_options"))
        self.menuFile.addAction(self.action_loadData)
        self.menuEdit.addAction(self.action_options)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_plot.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.tabWidget_plot.setTabText(self.tabWidget_plot.indexOf(self.tab_time), _translate("MainWindow", "Time", None))
        self.tabWidget_plot.setTabText(self.tabWidget_plot.indexOf(self.tab_frequency), _translate("MainWindow", "Frequency", None))
        self.tabWidget_plot.setTabText(self.tabWidget_plot.indexOf(self.tab_histogram), _translate("MainWindow", "Histogram", None))
        self.pushButton_loadData.setText(_translate("MainWindow", "Choose file", None))
        self.comboBox_columnSelect.setItemText(0, _translate("MainWindow", "Column 0", None))
        self.comboBox_columnSelect.setItemText(1, _translate("MainWindow", "Column 1", None))
        self.comboBox_columnSelect.setItemText(2, _translate("MainWindow", "Column 2", None))
        self.comboBox_columnSelect.setItemText(3, _translate("MainWindow", "Column 3", None))
        self.comboBox_columnSelect.setItemText(4, _translate("MainWindow", "Column 4", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.action_loadData.setText(_translate("MainWindow", "Load data", None))
        self.action_loadData.setShortcut(_translate("MainWindow", "Ctrl+L", None))
        self.action_options.setText(_translate("MainWindow", "Options", None))
        self.action_options.setShortcut(_translate("MainWindow", "Ctrl+P", None))

from pyqtgraph import PlotWidget
